name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20] # Test on multiple Node.js versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      

      - name: Print Secret (safe way)
        run: echo "The secret is set!"
        env:
          MY_SECRET_KEY: 'does this work'
          
      - name: Run tests
        run: npm test

      - name: Use Secret
        run: |
          echo "Using the secret securely."
          echo "${{ secrets.MY_SECRET_KEY }}" > secret_file.txt
